Add spec test for service host (failing).
Add a .feature file describing how to test the service host. Implement
the test steps generated for that .feature file. When run the test fails
with the following error:

error: There was no endpoint listening at http://localhost:8000/HelloIndigo/HelloIndigoService that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.

I believe this error results from different configuration for the
endpoint. Since I copied the configuration from the `ServiceFromScratch`
solution, I suspect I have something incorrect: perhaps spelling or a
different port number.

I decided to check in the code and work a bit more on the steps outlined
in the book, "Learning WCF," believing these steps will enlighten me. :)